### sign up
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation { signup(createUserData: { username: \"Omacr\", email: \"ccrnffhgbvfgnmnndnn@gmfaidl.com\", password: \"123456789\" }) { user { username, email, id }, token } }"
}

### Login
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation { login(email: \"ccrnffhgbvfgnmnndnn@gmfaidl.com\", password: \"123456789\") { user { username, email, id }, token } }"
}

### LoginAdmin
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation { loginAdmin(email: \"ccrnffhgbvfgnmnndnn@gmfaidl.com\", password: \"123456789\") { user { username, email, id }, token } }"
}

### Forgot Password 
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation { requestPasswordReset(email: \"omarahmedsabry05@gmail.com\") }"
}

### Reset Password
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation { resetPassword(token: \"359c1250a15f9f0a677de8656517c3853f3d6ea12f9a4f16fde058de3bfeec61\", newPassword: \"147258369\") }"
}

### Change Password
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation { changePassword(oldPassword: \"123456789\", newPassword: \"newPassword123\") }"
}

### LogOut
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation { logout }"
}

# http://localhost:3000/api/auth/google/login