###  create a product
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation { createProduct(createProductInput:{title: \"nSamplcfegce Prgoduct\",  category: \"omacvrahmedtsfom\",quantity:4, price: 100, description: \"This is a sample product\"}) { id title category image price description owner} }"
}

### Create Product with Image
POST http://localhost:3000/graphql
Content-Type: multipart/form-data

{
  "operations": {
    "query": "mutation ($createProductInput: CreateProductInput!, $file: Upload!) { createProduct(createProductInput: $createProductInput, file: $file) { id title description category price image owner { id username } } }",
    "variables": {
      "createProductInput": {
        "title": "Sample Product",
        "description": "A sample product description",
        "price": 58.99,
        "category": "Sample Category"
      },
      "file": null
    }
  },
  "map": {
    "0": ["variables.file"]
  },
  "0": "path/to/your/image.jpg"
}


### Get by id
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "query { getProductById(id: 1){ id title category image price description } }"
}

### update Product
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation { updateProduct( updateProductInput:{ category: \"j@gmail.com\"},id: 1 ) { id title description category } }"
}

### Delete User
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation { deleteProduct(id: 2) }"
}


### Create Product with Image Upload
POST http://localhost:3000/graphql
Content-Type: multipart/form-data

{
  "operations": {
    "query": "mutation ($createProductInput: CreateProductInput!, $file: Upload!) { createProduct(createProductInput: $createProductInput, file: $file) { id title description category price owner { id username } } }",
    "variables": {
      "createProductInput": {
        "title": "Sample Product",
        "description": "A sample product description",
        "price": 58.99,
        "category": "Sample Category"
      }
    }
  },
}


### Create Product with Image
POST http://localhost:3000/graphql
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
x-apollo-operation-name: createProduct
apollo-require-preflight: true

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="operations"

{
  "query": "mutation ($createProductInput: CreateProductInput!, $file: Upload!) { createProduct(createProductInput: $createProductInput, file: $file) { id title description category price image owner { id username } } }",
  "variables": {
    "createProductInput": {
      "title": "Sample Product",
      "description": "A sample product description",
      "price": 58.99,
      "category": "Sample Category"
    },
    "file": null
  }
}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="map"

{
  "0": ["variables.file"]
}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="0"; filename="image.jpg"
Content-Type: image/jpeg

<Replace this line with the content of your image file>
------WebKitFormBoundary7MA4YWxkTrZu0gW--
