### Get by id
POST http://localhost:3000/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNjcm5mZmhnYnZmZ25tbm5kbm5AZ21mYWlkbC5jb20iLCJpYXQiOjE3MzA3MTA3Mzd9.0zueXZgLef-LE1EsfU3MCd6bbJgh9hIkDHz116BDf_I

{
  "query": "query { getUserById(id: 37) { id username email } }"
}


### update Email
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation { updateEmail(  email: \"omavrahhvhgcmedtsfabry05@gmail.com\" ) { id username email } }"
}

### Delete User
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation { deleteUser(id: \"8\") }"
}


